/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ro.go.adrhc.springbootkstreamstutorial.adapters.topologies.profiles.messages;

/** profiles protocol */
@org.apache.avro.specific.AvroGenerated
public interface ProfilesProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ProfilesProtocol\",\"namespace\":\"ro.go.adrhc.springbootkstreamstutorial.adapters.topologies.profiles.messages\",\"doc\":\"profiles protocol\",\"types\":[{\"type\":\"record\",\"name\":\"ClientProfile\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"surname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"phone\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amountLimit\",\"type\":\"int\",\"default\":5},{\"name\":\"dailyMaxAmount\",\"type\":\"int\"},{\"name\":\"periodMaxAmount\",\"type\":\"int\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  /** profiles protocol */
  public interface Callback extends ProfilesProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = ro.go.adrhc.springbootkstreamstutorial.adapters.topologies.profiles.messages.ProfilesProtocol.PROTOCOL;
  }
}