/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class ClientProfile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientProfile\",\"namespace\":\"ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"surname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"phone\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"dailyMaxAmount\",\"type\":\"int\"},{\"name\":\"periodMaxAmount\",\"type\":\"int\"}]}");
	private static final long serialVersionUID = -905002886658350146L;
	private static SpecificData MODEL$ = new SpecificData();
	private static final BinaryMessageEncoder<ClientProfile> ENCODER =
			new BinaryMessageEncoder<ClientProfile>(MODEL$, SCHEMA$);
	private static final BinaryMessageDecoder<ClientProfile> DECODER =
			new BinaryMessageDecoder<ClientProfile>(MODEL$, SCHEMA$);
	@SuppressWarnings("unchecked")
	private static final org.apache.avro.io.DatumWriter<ClientProfile>
			WRITER$ = (org.apache.avro.io.DatumWriter<ClientProfile>) MODEL$.createDatumWriter(SCHEMA$);
	@SuppressWarnings("unchecked")
	private static final org.apache.avro.io.DatumReader<ClientProfile>
			READER$ = (org.apache.avro.io.DatumReader<ClientProfile>) MODEL$.createDatumReader(SCHEMA$);
	private java.lang.String id;
	private java.lang.String name;
	private java.lang.String surname;
	private java.lang.String email;
	private java.lang.String phone;
	private int dailyMaxAmount;
	private int periodMaxAmount;
	/**
	 * Default constructor.  Note that this does not initialize fields
	 * to their default values from the schema.  If that is desired then
	 * one should use <code>newBuilder()</code>.
	 */
	public ClientProfile() {}
	/**
	 * All-args constructor.
	 * @param id The new value for id
	 * @param name The new value for name
	 * @param surname The new value for surname
	 * @param email The new value for email
	 * @param phone The new value for phone
	 * @param dailyMaxAmount The new value for dailyMaxAmount
	 * @param periodMaxAmount The new value for periodMaxAmount
	 */
	public ClientProfile(java.lang.String id, java.lang.String name, java.lang.String surname, java.lang.String email, java.lang.String phone, java.lang.Integer dailyMaxAmount, java.lang.Integer periodMaxAmount) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.phone = phone;
		this.dailyMaxAmount = dailyMaxAmount;
		this.periodMaxAmount = periodMaxAmount;
	}

	public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

	/**
	 * Return the BinaryMessageEncoder instance used by this class.
	 * @return the message encoder used by this class
	 */
	public static BinaryMessageEncoder<ClientProfile> getEncoder() {
		return ENCODER;
	}

	/**
	 * Return the BinaryMessageDecoder instance used by this class.
	 * @return the message decoder used by this class
	 */
	public static BinaryMessageDecoder<ClientProfile> getDecoder() {
		return DECODER;
	}

	/**
	 * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
	 * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
	 * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
	 */
	public static BinaryMessageDecoder<ClientProfile> createDecoder(SchemaStore resolver) {
		return new BinaryMessageDecoder<ClientProfile>(MODEL$, SCHEMA$, resolver);
	}

	/**
	 * Deserializes a ClientProfile from a ByteBuffer.
	 * @param b a byte buffer holding serialized data for an instance of this class
	 * @return a ClientProfile instance decoded from the given buffer
	 * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
	 */
	public static ClientProfile fromByteBuffer(
			java.nio.ByteBuffer b) throws java.io.IOException {
		return DECODER.decode(b);
	}

	/**
	 * Creates a new ClientProfile RecordBuilder.
	 * @return A new ClientProfile RecordBuilder
	 */
	public static ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder newBuilder() {
		return new ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder();
	}

	/**
	 * Creates a new ClientProfile RecordBuilder by copying an existing Builder.
	 * @param other The existing builder to copy.
	 * @return A new ClientProfile RecordBuilder
	 */
	public static ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder newBuilder(ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder other) {
		if (other == null) {
			return new ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder();
		} else {
			return new ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder(other);
		}
	}

	/**
	 * Creates a new ClientProfile RecordBuilder by copying an existing ClientProfile instance.
	 * @param other The existing instance to copy.
	 * @return A new ClientProfile RecordBuilder
	 */
	public static ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder newBuilder(ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile other) {
		if (other == null) {
			return new ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder();
		} else {
			return new ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder(other);
		}
	}

	/**
	 * Serializes this ClientProfile to a ByteBuffer.
	 * @return a buffer holding the serialized data for this instance
	 * @throws java.io.IOException if this instance could not be serialized
	 */
	public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
		return ENCODER.encode(this);
	}

	public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

	public org.apache.avro.Schema getSchema() { return SCHEMA$; }

	// Used by DatumWriter.  Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
			case 0:
				return id;
			case 1:
				return name;
			case 2:
				return surname;
			case 3:
				return email;
			case 4:
				return phone;
			case 5:
				return dailyMaxAmount;
			case 6:
				return periodMaxAmount;
			default:
				throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader.  Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
			case 0:
				id = value$ != null ? value$.toString() : null;
				break;
			case 1:
				name = value$ != null ? value$.toString() : null;
				break;
			case 2:
				surname = value$ != null ? value$.toString() : null;
				break;
			case 3:
				email = value$ != null ? value$.toString() : null;
				break;
			case 4:
				phone = value$ != null ? value$.toString() : null;
				break;
			case 5:
				dailyMaxAmount = (java.lang.Integer) value$;
				break;
			case 6:
				periodMaxAmount = (java.lang.Integer) value$;
				break;
			default:
				throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	/**
	 * Gets the value of the 'id' field.
	 * @return The value of the 'id' field.
	 */
	public java.lang.String getId() {
		return id;
	}

	/**
	 * Sets the value of the 'id' field.
	 * @param value the value to set.
	 */
	public void setId(java.lang.String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the 'name' field.
	 * @return The value of the 'name' field.
	 */
	public java.lang.String getName() {
		return name;
	}

	/**
	 * Sets the value of the 'name' field.
	 * @param value the value to set.
	 */
	public void setName(java.lang.String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the 'surname' field.
	 * @return The value of the 'surname' field.
	 */
	public java.lang.String getSurname() {
		return surname;
	}

	/**
	 * Sets the value of the 'surname' field.
	 * @param value the value to set.
	 */
	public void setSurname(java.lang.String value) {
		this.surname = value;
	}

	/**
	 * Gets the value of the 'email' field.
	 * @return The value of the 'email' field.
	 */
	public java.lang.String getEmail() {
		return email;
	}

	/**
	 * Sets the value of the 'email' field.
	 * @param value the value to set.
	 */
	public void setEmail(java.lang.String value) {
		this.email = value;
	}

	/**
	 * Gets the value of the 'phone' field.
	 * @return The value of the 'phone' field.
	 */
	public java.lang.String getPhone() {
		return phone;
	}

	/**
	 * Sets the value of the 'phone' field.
	 * @param value the value to set.
	 */
	public void setPhone(java.lang.String value) {
		this.phone = value;
	}

	/**
	 * Gets the value of the 'dailyMaxAmount' field.
	 * @return The value of the 'dailyMaxAmount' field.
	 */
	public int getDailyMaxAmount() {
		return dailyMaxAmount;
	}

	/**
	 * Sets the value of the 'dailyMaxAmount' field.
	 * @param value the value to set.
	 */
	public void setDailyMaxAmount(int value) {
		this.dailyMaxAmount = value;
	}

	/**
	 * Gets the value of the 'periodMaxAmount' field.
	 * @return The value of the 'periodMaxAmount' field.
	 */
	public int getPeriodMaxAmount() {
		return periodMaxAmount;
	}

	/**
	 * Sets the value of the 'periodMaxAmount' field.
	 * @param value the value to set.
	 */
	public void setPeriodMaxAmount(int value) {
		this.periodMaxAmount = value;
	}

	@Override
	public void writeExternal(java.io.ObjectOutput out)
			throws java.io.IOException {
		WRITER$.write(this, SpecificData.getEncoder(out));
	}

	@Override
	public void readExternal(java.io.ObjectInput in)
			throws java.io.IOException {
		READER$.read(this, SpecificData.getDecoder(in));
	}

	@Override
	protected boolean hasCustomCoders() { return true; }

	@Override
	public void customEncode(org.apache.avro.io.Encoder out)
			throws java.io.IOException {
		out.writeString(this.id);

		out.writeString(this.name);

		out.writeString(this.surname);

		out.writeString(this.email);

		out.writeString(this.phone);

		out.writeInt(this.dailyMaxAmount);

		out.writeInt(this.periodMaxAmount);

	}

	@Override
	public void customDecode(org.apache.avro.io.ResolvingDecoder in)
			throws java.io.IOException {
		org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
		if (fieldOrder == null) {
			this.id = in.readString();

			this.name = in.readString();

			this.surname = in.readString();

			this.email = in.readString();

			this.phone = in.readString();

			this.dailyMaxAmount = in.readInt();

			this.periodMaxAmount = in.readInt();

		} else {
			for (int i = 0; i < 7; i++) {
				switch (fieldOrder[i].pos()) {
					case 0:
						this.id = in.readString();
						break;

					case 1:
						this.name = in.readString();
						break;

					case 2:
						this.surname = in.readString();
						break;

					case 3:
						this.email = in.readString();
						break;

					case 4:
						this.phone = in.readString();
						break;

					case 5:
						this.dailyMaxAmount = in.readInt();
						break;

					case 6:
						this.periodMaxAmount = in.readInt();
						break;

					default:
						throw new java.io.IOException("Corrupt ResolvingDecoder.");
				}
			}
		}
	}

	/**
	 * RecordBuilder for ClientProfile instances.
	 */
	@org.apache.avro.specific.AvroGenerated
	public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientProfile>
			implements org.apache.avro.data.RecordBuilder<ClientProfile> {

		private java.lang.String id;
		private java.lang.String name;
		private java.lang.String surname;
		private java.lang.String email;
		private java.lang.String phone;
		private int dailyMaxAmount;
		private int periodMaxAmount;

		/** Creates a new Builder */
		private Builder() {
			super(SCHEMA$);
		}

		/**
		 * Creates a Builder by copying an existing Builder.
		 * @param other The existing Builder to copy.
		 */
		private Builder(ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder other) {
			super(other);
			if (isValidValue(fields()[0], other.id)) {
				this.id = data().deepCopy(fields()[0].schema(), other.id);
				fieldSetFlags()[0] = other.fieldSetFlags()[0];
			}
			if (isValidValue(fields()[1], other.name)) {
				this.name = data().deepCopy(fields()[1].schema(), other.name);
				fieldSetFlags()[1] = other.fieldSetFlags()[1];
			}
			if (isValidValue(fields()[2], other.surname)) {
				this.surname = data().deepCopy(fields()[2].schema(), other.surname);
				fieldSetFlags()[2] = other.fieldSetFlags()[2];
			}
			if (isValidValue(fields()[3], other.email)) {
				this.email = data().deepCopy(fields()[3].schema(), other.email);
				fieldSetFlags()[3] = other.fieldSetFlags()[3];
			}
			if (isValidValue(fields()[4], other.phone)) {
				this.phone = data().deepCopy(fields()[4].schema(), other.phone);
				fieldSetFlags()[4] = other.fieldSetFlags()[4];
			}
			if (isValidValue(fields()[5], other.dailyMaxAmount)) {
				this.dailyMaxAmount = data().deepCopy(fields()[5].schema(), other.dailyMaxAmount);
				fieldSetFlags()[5] = other.fieldSetFlags()[5];
			}
			if (isValidValue(fields()[6], other.periodMaxAmount)) {
				this.periodMaxAmount = data().deepCopy(fields()[6].schema(), other.periodMaxAmount);
				fieldSetFlags()[6] = other.fieldSetFlags()[6];
			}
		}

		/**
		 * Creates a Builder by copying an existing ClientProfile instance
		 * @param other The existing instance to copy.
		 */
		private Builder(ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile other) {
			super(SCHEMA$);
			if (isValidValue(fields()[0], other.id)) {
				this.id = data().deepCopy(fields()[0].schema(), other.id);
				fieldSetFlags()[0] = true;
			}
			if (isValidValue(fields()[1], other.name)) {
				this.name = data().deepCopy(fields()[1].schema(), other.name);
				fieldSetFlags()[1] = true;
			}
			if (isValidValue(fields()[2], other.surname)) {
				this.surname = data().deepCopy(fields()[2].schema(), other.surname);
				fieldSetFlags()[2] = true;
			}
			if (isValidValue(fields()[3], other.email)) {
				this.email = data().deepCopy(fields()[3].schema(), other.email);
				fieldSetFlags()[3] = true;
			}
			if (isValidValue(fields()[4], other.phone)) {
				this.phone = data().deepCopy(fields()[4].schema(), other.phone);
				fieldSetFlags()[4] = true;
			}
			if (isValidValue(fields()[5], other.dailyMaxAmount)) {
				this.dailyMaxAmount = data().deepCopy(fields()[5].schema(), other.dailyMaxAmount);
				fieldSetFlags()[5] = true;
			}
			if (isValidValue(fields()[6], other.periodMaxAmount)) {
				this.periodMaxAmount = data().deepCopy(fields()[6].schema(), other.periodMaxAmount);
				fieldSetFlags()[6] = true;
			}
		}

		/**
		 * Gets the value of the 'id' field.
		 * @return The value.
		 */
		public java.lang.String getId() {
			return id;
		}


		/**
		 * Sets the value of the 'id' field.
		 * @param value The value of 'id'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setId(java.lang.String value) {
			validate(fields()[0], value);
			this.id = value;
			fieldSetFlags()[0] = true;
			return this;
		}

		/**
		 * Checks whether the 'id' field has been set.
		 * @return True if the 'id' field has been set, false otherwise.
		 */
		public boolean hasId() {
			return fieldSetFlags()[0];
		}


		/**
		 * Clears the value of the 'id' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearId() {
			id = null;
			fieldSetFlags()[0] = false;
			return this;
		}

		/**
		 * Gets the value of the 'name' field.
		 * @return The value.
		 */
		public java.lang.String getName() {
			return name;
		}


		/**
		 * Sets the value of the 'name' field.
		 * @param value The value of 'name'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setName(java.lang.String value) {
			validate(fields()[1], value);
			this.name = value;
			fieldSetFlags()[1] = true;
			return this;
		}

		/**
		 * Checks whether the 'name' field has been set.
		 * @return True if the 'name' field has been set, false otherwise.
		 */
		public boolean hasName() {
			return fieldSetFlags()[1];
		}


		/**
		 * Clears the value of the 'name' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearName() {
			name = null;
			fieldSetFlags()[1] = false;
			return this;
		}

		/**
		 * Gets the value of the 'surname' field.
		 * @return The value.
		 */
		public java.lang.String getSurname() {
			return surname;
		}


		/**
		 * Sets the value of the 'surname' field.
		 * @param value The value of 'surname'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setSurname(java.lang.String value) {
			validate(fields()[2], value);
			this.surname = value;
			fieldSetFlags()[2] = true;
			return this;
		}

		/**
		 * Checks whether the 'surname' field has been set.
		 * @return True if the 'surname' field has been set, false otherwise.
		 */
		public boolean hasSurname() {
			return fieldSetFlags()[2];
		}


		/**
		 * Clears the value of the 'surname' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearSurname() {
			surname = null;
			fieldSetFlags()[2] = false;
			return this;
		}

		/**
		 * Gets the value of the 'email' field.
		 * @return The value.
		 */
		public java.lang.String getEmail() {
			return email;
		}


		/**
		 * Sets the value of the 'email' field.
		 * @param value The value of 'email'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setEmail(java.lang.String value) {
			validate(fields()[3], value);
			this.email = value;
			fieldSetFlags()[3] = true;
			return this;
		}

		/**
		 * Checks whether the 'email' field has been set.
		 * @return True if the 'email' field has been set, false otherwise.
		 */
		public boolean hasEmail() {
			return fieldSetFlags()[3];
		}


		/**
		 * Clears the value of the 'email' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearEmail() {
			email = null;
			fieldSetFlags()[3] = false;
			return this;
		}

		/**
		 * Gets the value of the 'phone' field.
		 * @return The value.
		 */
		public java.lang.String getPhone() {
			return phone;
		}


		/**
		 * Sets the value of the 'phone' field.
		 * @param value The value of 'phone'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setPhone(java.lang.String value) {
			validate(fields()[4], value);
			this.phone = value;
			fieldSetFlags()[4] = true;
			return this;
		}

		/**
		 * Checks whether the 'phone' field has been set.
		 * @return True if the 'phone' field has been set, false otherwise.
		 */
		public boolean hasPhone() {
			return fieldSetFlags()[4];
		}


		/**
		 * Clears the value of the 'phone' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearPhone() {
			phone = null;
			fieldSetFlags()[4] = false;
			return this;
		}

		/**
		 * Gets the value of the 'dailyMaxAmount' field.
		 * @return The value.
		 */
		public int getDailyMaxAmount() {
			return dailyMaxAmount;
		}


		/**
		 * Sets the value of the 'dailyMaxAmount' field.
		 * @param value The value of 'dailyMaxAmount'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setDailyMaxAmount(int value) {
			validate(fields()[5], value);
			this.dailyMaxAmount = value;
			fieldSetFlags()[5] = true;
			return this;
		}

		/**
		 * Checks whether the 'dailyMaxAmount' field has been set.
		 * @return True if the 'dailyMaxAmount' field has been set, false otherwise.
		 */
		public boolean hasDailyMaxAmount() {
			return fieldSetFlags()[5];
		}


		/**
		 * Clears the value of the 'dailyMaxAmount' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearDailyMaxAmount() {
			fieldSetFlags()[5] = false;
			return this;
		}

		/**
		 * Gets the value of the 'periodMaxAmount' field.
		 * @return The value.
		 */
		public int getPeriodMaxAmount() {
			return periodMaxAmount;
		}


		/**
		 * Sets the value of the 'periodMaxAmount' field.
		 * @param value The value of 'periodMaxAmount'.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder setPeriodMaxAmount(int value) {
			validate(fields()[6], value);
			this.periodMaxAmount = value;
			fieldSetFlags()[6] = true;
			return this;
		}

		/**
		 * Checks whether the 'periodMaxAmount' field has been set.
		 * @return True if the 'periodMaxAmount' field has been set, false otherwise.
		 */
		public boolean hasPeriodMaxAmount() {
			return fieldSetFlags()[6];
		}


		/**
		 * Clears the value of the 'periodMaxAmount' field.
		 * @return This builder.
		 */
		public ro.go.adrhc.springbootkstreamstutorial.infrastructure.topologies.profiles.messages.ClientProfile.Builder clearPeriodMaxAmount() {
			fieldSetFlags()[6] = false;
			return this;
		}

		@Override
		@SuppressWarnings("unchecked")
		public ClientProfile build() {
			try {
				ClientProfile record = new ClientProfile();
				record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
				record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
				record.surname = fieldSetFlags()[2] ? this.surname : (java.lang.String) defaultValue(fields()[2]);
				record.email = fieldSetFlags()[3] ? this.email : (java.lang.String) defaultValue(fields()[3]);
				record.phone = fieldSetFlags()[4] ? this.phone : (java.lang.String) defaultValue(fields()[4]);
				record.dailyMaxAmount = fieldSetFlags()[5] ? this.dailyMaxAmount : (java.lang.Integer) defaultValue(fields()[5]);
				record.periodMaxAmount = fieldSetFlags()[6] ? this.periodMaxAmount : (java.lang.Integer) defaultValue(fields()[6]);
				return record;
			} catch (org.apache.avro.AvroMissingFieldException e) {
				throw e;
			} catch (java.lang.Exception e) {
				throw new org.apache.avro.AvroRuntimeException(e);
			}
		}
	}
}










